-- MySQL Script generated by MySQL Workbench
-- 03/10/16 11:50:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LePrAtos_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LePrAtos_DB` ;

-- -----------------------------------------------------
-- Schema LePrAtos_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LePrAtos_DB` DEFAULT CHARACTER SET utf8 ;
USE `LePrAtos_DB` ;

-- -----------------------------------------------------
-- Table `LePrAtos_DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LePrAtos_DB`.`User` (
  `ID_User` VARCHAR(36) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_User`),
  UNIQUE INDEX `ID_USER_UNIQUE` (`ID_User` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));


-- -----------------------------------------------------
-- Table `LePrAtos_DB`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LePrAtos_DB`.`Game` (
  `ID_Game` INT NOT NULL AUTO_INCREMENT,
  `Start` DATETIME NOT NULL,
  `End` DATETIME NULL,
  PRIMARY KEY (`ID_Game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LePrAtos_DB`.`Stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LePrAtos_DB`.`Stats` (
  `ID_Stats` INT NOT NULL AUTO_INCREMENT,
  `AmountWhool` INT NULL,
  `AmountIron` INT NULL,
  `AmountWood` INT NULL,
  `AmountGrain` INT NULL,
  `AmountHouses` INT NULL,
  `AmountTowns` INT NULL,
  `AmountStreets` INT NULL,
  PRIMARY KEY (`ID_Stats`),
  UNIQUE INDEX `ID_Stats_UNIQUE` (`ID_Stats` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LePrAtos_DB`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LePrAtos_DB`.`Participant` (
  `ID_Participant` INT NOT NULL AUTO_INCREMENT,
  `FK_User` VARCHAR(36) NOT NULL,
  `FK_Games` INT NOT NULL,
  `FK_Stats` INT NOT NULL,
  PRIMARY KEY (`ID_Participant`),
  UNIQUE INDEX `ID_Participant_UNIQUE` (`ID_Participant` ASC),
  INDEX `fk_Participants_User_idx` (`FK_User` ASC),
  INDEX `fk_Participants_Games1_idx` (`FK_Games` ASC),
  INDEX `fk_Participants_Stats1_idx` (`FK_Stats` ASC),
  CONSTRAINT `fk_Participants_User`
    FOREIGN KEY (`FK_User`)
    REFERENCES `LePrAtos_DB`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participants_Games1`
    FOREIGN KEY (`FK_Games`)
    REFERENCES `LePrAtos_DB`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participants_Stats1`
    FOREIGN KEY (`FK_Stats`)
    REFERENCES `LePrAtos_DB`.`Stats` (`ID_Stats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LePrAtos_DB`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LePrAtos_DB`.`Card` (
  `ID_Card` VARCHAR(10) NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`ID_Card`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LePrAtos_DB`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LePrAtos_DB`.`Building` (
  `ID_Building` VARCHAR(10) NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`ID_Building`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
